--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

-- Started on 2024-09-08 01:04:59

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16437)
-- Name: chatmessages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chatmessages (
    id bigint NOT NULL,
    uid bigint,
    message character varying,
    "timestamp" character varying
);


ALTER TABLE public.chatmessages OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16473)
-- Name: files; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.files (
    id integer NOT NULL,
    uid bigint,
    label character varying,
    filename character varying
);


ALTER TABLE public.files OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16472)
-- Name: files_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.files_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.files_id_seq OWNER TO postgres;

--
-- TOC entry 4858 (class 0 OID 0)
-- Dependencies: 217
-- Name: files_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.files_id_seq OWNED BY public.files.id;


--
-- TOC entry 215 (class 1259 OID 16430)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying,
    email character varying,
    password character varying,
    date_added timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    token character varying
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16495)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4698 (class 2604 OID 16476)
-- Name: files id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.files ALTER COLUMN id SET DEFAULT nextval('public.files_id_seq'::regclass);


--
-- TOC entry 4849 (class 0 OID 16437)
-- Dependencies: 216
-- Data for Name: chatmessages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chatmessages (id, uid, message, "timestamp") FROM stdin;
1725164870336	1725014695710	hi	1725164870336
1725164914126	1725017451740	hi amol kay krto	1725164914126
1725694020871	1725014695710	hi	1725694020871
1725729951208	1725726229240	hi	1725729951208
1725729956161	1725726229240	hiii	1725729956161
1725730469677	1725726229240	hello	1725730469677
1725730474668	1725726229240	hello, how are you ????????????	1725730474668
1725730650312	1725730635742	hi	1725730650312
1725737193155	1725731317578	hi	1725737193155
\.


--
-- TOC entry 4851 (class 0 OID 16473)
-- Dependencies: 218
-- Data for Name: files; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.files (id, uid, label, filename) FROM stdin;
1	1725014695710	register	Screenshot 2024-04-05 155033.png
2	1725014695710	register	Screenshot 2024-04-05 155033.png
3	1725014695710	register	Screenshot 2024-04-05 155232.png
4	1725731317578	Amol	download.htm
6	1725731317578	file1	download.htm
8	1725731317578	new file	download.htm
9	1725731317578	new file new	download.htm
\.


--
-- TOC entry 4848 (class 0 OID 16430)
-- Dependencies: 215
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name, email, password, date_added, token) FROM stdin;
1725731317578	kanchan kadam	molkadam@gmail.com	$2b$10$zkucJwD2eWBq2AO3nraqdOpWI08LhX2T8DfQrepbNf9V8AqgOajt6	2024-09-07 23:18:38.022845	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3MjU3MzEzMTc1NzgiLCJpYXQiOjE3MjU3MzY5MzgsImV4cCI6MTcyNTc0MDUzOH0.xVUv8ebuBW2vKbJEKRyQ-3mXuw9b_dscgKIC1DfzGEA
\.


--
-- TOC entry 4859 (class 0 OID 0)
-- Dependencies: 217
-- Name: files_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.files_id_seq', 9, true);


--
-- TOC entry 4860 (class 0 OID 0)
-- Dependencies: 219
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 4702 (class 2606 OID 16443)
-- Name: chatmessages chatMessages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chatmessages
    ADD CONSTRAINT "chatMessages_pkey" PRIMARY KEY (id);


--
-- TOC entry 4704 (class 2606 OID 16480)
-- Name: files files_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_pkey PRIMARY KEY (id);


--
-- TOC entry 4700 (class 2606 OID 16436)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


-- Completed on 2024-09-08 01:05:00

--
-- PostgreSQL database dump complete
--

